name: Docker Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: node:current-alpine
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        image: [golbian/managerr-back]

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ matrix.image }}
          # generate Docker tags based on the following events/attributes
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: golbian
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "GITHUB_SHA=${GITHUB_SHA}"
            "GITHUB_REF=${GITHUB_REF}"
            "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
